name: Build Orion

on:
  push:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # or: 'beta', 'dev', 'master' (or 'main')
          flutter-version: 3.32.8
      - run: sudo apt-get update && sudo apt-get install -y gtk+-3.0
      - run: flutter pub global activate flutterpi_tool

      # Add these steps to verify and fix localization files
      - name: Verify ARB Localization Files
        run: |
          echo "Checking ARB files for locale mismatches..."
          for file in lib/l10n/app_*.arb; do
            locale=$(basename $file | sed 's/app_\(.*\)\.arb/\1/')
            if [ "$locale" == "" ]; then continue; fi
            
            # Extract the @@locale value from the ARB file
            file_locale=$(grep -o '"@@locale": *"[^"]*"' $file | cut -d'"' -f4)
            
            # If the locale values don't match, update the file
            if [ "$file_locale" != "$locale" ]; then
              echo "Fixing locale mismatch in $file: changing $file_locale to $locale"
              sed -i 's/"@@locale": *"[^"]*"/"@@locale": "'$locale'"/' $file
            fi
          done

      # Generate localization files
      - name: Generate Localizations
        run: flutter gen-l10n

      - run: flutter build linux

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(yq '.version' pubspec.yaml)
          # Strip build metadata if it exists
          VERSION=$(echo $VERSION | sed 's/+.*//')
          echo "result=$VERSION" >> $GITHUB_OUTPUT

      - name: Update Version with Commit Hash
        run: |
          VERSION=$(yq '.version' pubspec.yaml)
          COMMIT_HASH=${GITHUB_SHA::7}
          NEW_VERSION=${VERSION/+SELFCOMPILED/+${COMMIT_HASH}}
          yq -i ".version = \"$NEW_VERSION\"" pubspec.yaml
          echo "Updated version to $NEW_VERSION"

      - name: Run pubspec_extract
        run: flutter pub run pubspec_extract

      - name: Build, Copy, and Compress armv7
        run: |
          BUILD_NAME=orion_armv7
          flutterpi_tool build --release
          mv build/flutter_assets $BUILD_NAME
          ( cd $BUILD_NAME && tar -czvf $BUILD_NAME.tar.gz * )
          cp $BUILD_NAME/$BUILD_NAME.tar.gz $BUILD_NAME.tar.gz

      - uses: actions/upload-artifact@v4.3.1
        with:
          name: orion_armv7
          path: orion_armv7/*

      - name: Build, Copy, and Compress aarch64
        run: |
          BUILD_NAME=orion_aarch64
          flutterpi_tool build --arch=arm64 --release
          mv build/flutter_assets $BUILD_NAME
          ( cd $BUILD_NAME && tar -czvf $BUILD_NAME.tar.gz * )
          cp $BUILD_NAME/$BUILD_NAME.tar.gz $BUILD_NAME.tar.gz

      - uses: actions/upload-artifact@v4.3.1
        with:
          name: orion_aarch64
          path: orion_aarch64/*

      - name: Build, Copy, and Compress x64
        run: |
          BUILD_NAME=orion_x64
          flutterpi_tool build --arch=x64 --release
          mv build/flutter_assets $BUILD_NAME
          ( cd $BUILD_NAME && tar -czvf $BUILD_NAME.tar.gz * )
          cp $BUILD_NAME/$BUILD_NAME.tar.gz $BUILD_NAME.tar.gz

      - uses: actions/upload-artifact@v4.3.1
        with:
          name: orion_x64
          path: orion_x64/*

      - uses: ncipollo/release-action@v1.14.0
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: orion*.tar.gz
          tag: v${{ steps.get_version.outputs.result }}
          skipIfReleaseExists: true
          generateReleaseNotes: true
          commit: ${{github.sha}}

      - uses: ncipollo/release-action@v1.14.0
        if: github.ref != 'refs/heads/main'
        with:
          artifacts: orion*.tar.gz
          tag: BRANCH_${{github.ref_name}}
          skipIfReleaseExists: false
          allowUpdates: true
          prerelease: true
          generateReleaseNotes: true
          commit: ${{github.sha}}
