name: Build Odyssey

on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev', 'master' (or 'main')
      - run: sudo apt-get update && apt-get install -y gtk+-3.0
      - run: pwd
      - run: flutter pub global activate flutterpi_tool
      - run: flutter build linux
      - run: flutterpi_tool build --arch=arm64 --cpu=pi4 --release


      - name: Copy & Compress output
        id: compress
        run: |
          cp target/armv7-unknown-linux-gnueabihf/release/odyssey odyssey
          cp target/armv7-unknown-linux-gnueabihf/release/odyssey.yaml odyssey.yaml
          cp target/armv7-unknown-linux-gnueabihf/release/apiHelper.py apiHelper.py
          tar -czvf orion.tar.gz build/flutter_assets
          echo "archive=$ARCHIVE" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4.3.1
        with:
          name: orion
          path: |
            orion.tar.gz

      - uses: ncipollo/release-action@v1.14.0
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: orion.tar.gz
          tag: v1
          skipIfReleaseExists: true
          generateReleaseNotes: true
          commit: ${{github.sha}}
      - uses: ncipollo/release-action@v1.14.0
        if: github.ref != 'refs/heads/main'
        with:
          artifacts: orion.tar.gz
          tag: BRANCH_${{github.ref_name}}
          skipIfReleaseExists: false
          allowUpdates: true
          prerelease: true
          generateReleaseNotes: true
          commit: ${{github.sha}}
